<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Override Directory.Build.props to multi-target -->
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <!-- Optionally, set a few things to your liking -->
    <MajorVersion>0</MajorVersion>
    <MinorVersion>1</MinorVersion>
    <IsMod>false</IsMod>
    <IsPlugin>false</IsPlugin>
    <PackageMod>false</PackageMod>
    <PublishMod>false</PublishMod>
    <Configurations>Debug;Release;PrivateTesting;Testing</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='PrivateTesting|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Testing|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JsonSubTypes" Version="2.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>
</Project>
